spring:
  application:
    name: civicpulse-nexus-api

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:}
    password: ${GMAIL_APP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/civicpulse

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: civicpulse-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"

server:
  port: 8081

  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.civicpulse.nexus: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
  server-url: http://localhost:8180

  realm: civicpulse

  admin:
    realm: master
    client-id: admin-cli
    username: admin
    password: admin

  client:
    client-id: civicpulse-api
    client-secret: zvtO7T30rtQRtNkXnQ8Gyzjz0k46kTox
