/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedComplaintsIndexRouteImport } from './routes/_authenticated.complaints.index'
import { Route as AuthenticatedServicesApplyRouteImport } from './routes/_authenticated.services.apply'
import { Route as AuthenticatedServicesApplicationsRouteImport } from './routes/_authenticated.services.applications'
import { Route as AuthenticatedOfficerServicesRouteImport } from './routes/_authenticated.officer.services'
import { Route as AuthenticatedOfficerDashboardRouteImport } from './routes/_authenticated.officer.dashboard'
import { Route as AuthenticatedOfficerAssignedRouteImport } from './routes/_authenticated.officer.assigned'
import { Route as AuthenticatedComplaintsCreateRouteImport } from './routes/_authenticated.complaints.create'
import { Route as AuthenticatedComplaintsIdRouteImport } from './routes/_authenticated.complaints.$id'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated.admin.services'
import { Route as AuthenticatedAdminOfficersRouteImport } from './routes/_authenticated.admin.officers'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated.admin.departments'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAdminComplaintsRouteImport } from './routes/_authenticated.admin.complaints'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated.admin.categories'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated.admin.analytics'
import { Route as AuthenticatedServicesApplicationDetailsIdRouteImport } from './routes/_authenticated.services.application-details.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComplaintsIndexRoute =
  AuthenticatedComplaintsIndexRouteImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesApplyRoute =
  AuthenticatedServicesApplyRouteImport.update({
    id: '/services/apply',
    path: '/services/apply',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesApplicationsRoute =
  AuthenticatedServicesApplicationsRouteImport.update({
    id: '/services/applications',
    path: '/services/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfficerServicesRoute =
  AuthenticatedOfficerServicesRouteImport.update({
    id: '/officer/services',
    path: '/officer/services',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfficerDashboardRoute =
  AuthenticatedOfficerDashboardRouteImport.update({
    id: '/officer/dashboard',
    path: '/officer/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfficerAssignedRoute =
  AuthenticatedOfficerAssignedRouteImport.update({
    id: '/officer/assigned',
    path: '/officer/assigned',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplaintsCreateRoute =
  AuthenticatedComplaintsCreateRouteImport.update({
    id: '/complaints/create',
    path: '/complaints/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplaintsIdRoute =
  AuthenticatedComplaintsIdRouteImport.update({
    id: '/complaints/$id',
    path: '/complaints/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOfficersRoute =
  AuthenticatedAdminOfficersRouteImport.update({
    id: '/admin/officers',
    path: '/admin/officers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminComplaintsRoute =
  AuthenticatedAdminComplaintsRouteImport.update({
    id: '/admin/complaints',
    path: '/admin/complaints',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesApplicationDetailsIdRoute =
  AuthenticatedServicesApplicationDetailsIdRouteImport.update({
    id: '/services/application-details/$id',
    path: '/services/application-details/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/officers': typeof AuthenticatedAdminOfficersRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/complaints/create': typeof AuthenticatedComplaintsCreateRoute
  '/officer/assigned': typeof AuthenticatedOfficerAssignedRoute
  '/officer/dashboard': typeof AuthenticatedOfficerDashboardRoute
  '/officer/services': typeof AuthenticatedOfficerServicesRoute
  '/services/applications': typeof AuthenticatedServicesApplicationsRoute
  '/services/apply': typeof AuthenticatedServicesApplyRoute
  '/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/services/application-details/$id': typeof AuthenticatedServicesApplicationDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/officers': typeof AuthenticatedAdminOfficersRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/complaints/create': typeof AuthenticatedComplaintsCreateRoute
  '/officer/assigned': typeof AuthenticatedOfficerAssignedRoute
  '/officer/dashboard': typeof AuthenticatedOfficerDashboardRoute
  '/officer/services': typeof AuthenticatedOfficerServicesRoute
  '/services/applications': typeof AuthenticatedServicesApplicationsRoute
  '/services/apply': typeof AuthenticatedServicesApplyRoute
  '/complaints': typeof AuthenticatedComplaintsIndexRoute
  '/services/application-details/$id': typeof AuthenticatedServicesApplicationDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/officers': typeof AuthenticatedAdminOfficersRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/_authenticated/complaints/create': typeof AuthenticatedComplaintsCreateRoute
  '/_authenticated/officer/assigned': typeof AuthenticatedOfficerAssignedRoute
  '/_authenticated/officer/dashboard': typeof AuthenticatedOfficerDashboardRoute
  '/_authenticated/officer/services': typeof AuthenticatedOfficerServicesRoute
  '/_authenticated/services/applications': typeof AuthenticatedServicesApplicationsRoute
  '/_authenticated/services/apply': typeof AuthenticatedServicesApplyRoute
  '/_authenticated/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/_authenticated/services/application-details/$id': typeof AuthenticatedServicesApplicationDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/officers'
    | '/admin/services'
    | '/complaints/$id'
    | '/complaints/create'
    | '/officer/assigned'
    | '/officer/dashboard'
    | '/officer/services'
    | '/services/applications'
    | '/services/apply'
    | '/complaints/'
    | '/services/application-details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/officers'
    | '/admin/services'
    | '/complaints/$id'
    | '/complaints/create'
    | '/officer/assigned'
    | '/officer/dashboard'
    | '/officer/services'
    | '/services/applications'
    | '/services/apply'
    | '/complaints'
    | '/services/application-details/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/complaints'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/officers'
    | '/_authenticated/admin/services'
    | '/_authenticated/complaints/$id'
    | '/_authenticated/complaints/create'
    | '/_authenticated/officer/assigned'
    | '/_authenticated/officer/dashboard'
    | '/_authenticated/officer/services'
    | '/_authenticated/services/applications'
    | '/_authenticated/services/apply'
    | '/_authenticated/complaints/'
    | '/_authenticated/services/application-details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints/': {
      id: '/_authenticated/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AuthenticatedComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/apply': {
      id: '/_authenticated/services/apply'
      path: '/services/apply'
      fullPath: '/services/apply'
      preLoaderRoute: typeof AuthenticatedServicesApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/applications': {
      id: '/_authenticated/services/applications'
      path: '/services/applications'
      fullPath: '/services/applications'
      preLoaderRoute: typeof AuthenticatedServicesApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/officer/services': {
      id: '/_authenticated/officer/services'
      path: '/officer/services'
      fullPath: '/officer/services'
      preLoaderRoute: typeof AuthenticatedOfficerServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/officer/dashboard': {
      id: '/_authenticated/officer/dashboard'
      path: '/officer/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof AuthenticatedOfficerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/officer/assigned': {
      id: '/_authenticated/officer/assigned'
      path: '/officer/assigned'
      fullPath: '/officer/assigned'
      preLoaderRoute: typeof AuthenticatedOfficerAssignedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints/create': {
      id: '/_authenticated/complaints/create'
      path: '/complaints/create'
      fullPath: '/complaints/create'
      preLoaderRoute: typeof AuthenticatedComplaintsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints/$id': {
      id: '/_authenticated/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthenticatedComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/officers': {
      id: '/_authenticated/admin/officers'
      path: '/admin/officers'
      fullPath: '/admin/officers'
      preLoaderRoute: typeof AuthenticatedAdminOfficersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/complaints': {
      id: '/_authenticated/admin/complaints'
      path: '/admin/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AuthenticatedAdminComplaintsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/application-details/$id': {
      id: '/_authenticated/services/application-details/$id'
      path: '/services/application-details/$id'
      fullPath: '/services/application-details/$id'
      preLoaderRoute: typeof AuthenticatedServicesApplicationDetailsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminComplaintsRoute: typeof AuthenticatedAdminComplaintsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminOfficersRoute: typeof AuthenticatedAdminOfficersRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedComplaintsIdRoute: typeof AuthenticatedComplaintsIdRoute
  AuthenticatedComplaintsCreateRoute: typeof AuthenticatedComplaintsCreateRoute
  AuthenticatedOfficerAssignedRoute: typeof AuthenticatedOfficerAssignedRoute
  AuthenticatedOfficerDashboardRoute: typeof AuthenticatedOfficerDashboardRoute
  AuthenticatedOfficerServicesRoute: typeof AuthenticatedOfficerServicesRoute
  AuthenticatedServicesApplicationsRoute: typeof AuthenticatedServicesApplicationsRoute
  AuthenticatedServicesApplyRoute: typeof AuthenticatedServicesApplyRoute
  AuthenticatedComplaintsIndexRoute: typeof AuthenticatedComplaintsIndexRoute
  AuthenticatedServicesApplicationDetailsIdRoute: typeof AuthenticatedServicesApplicationDetailsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminComplaintsRoute: AuthenticatedAdminComplaintsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminOfficersRoute: AuthenticatedAdminOfficersRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedComplaintsIdRoute: AuthenticatedComplaintsIdRoute,
  AuthenticatedComplaintsCreateRoute: AuthenticatedComplaintsCreateRoute,
  AuthenticatedOfficerAssignedRoute: AuthenticatedOfficerAssignedRoute,
  AuthenticatedOfficerDashboardRoute: AuthenticatedOfficerDashboardRoute,
  AuthenticatedOfficerServicesRoute: AuthenticatedOfficerServicesRoute,
  AuthenticatedServicesApplicationsRoute:
    AuthenticatedServicesApplicationsRoute,
  AuthenticatedServicesApplyRoute: AuthenticatedServicesApplyRoute,
  AuthenticatedComplaintsIndexRoute: AuthenticatedComplaintsIndexRoute,
  AuthenticatedServicesApplicationDetailsIdRoute:
    AuthenticatedServicesApplicationDetailsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
